---
- name: install prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates 
      - curl 
      - gnupg-agent
      - software-properties-common
    update_cache: yes

- name: add apt-key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: add docker repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable

- name: install docker 
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

# Installs Docker SDK
- name: install python package manager
  apt:
    name: python3-pip

- name: install python sdk
  become_user: "{{ user_for_groups }}"
  pip:
    name:
      - docker
      - docker-compose

- name: Add user "{{ user_for_groups }}" to docker group
  user: 
    name: "{{ user_for_groups }}"
    group: docker
    append: yes