# -*- mode: ruby -*-
# vi: set ft=ruby :

NODES_NUMBER = 3

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
    (1..NODES_NUMBER).each do |i|
        config.vm.define "node-#{i}" do |docker|
            docker.vm.box = "generic/ubuntu2004"
            docker.vm.hostname = "node-#{i}.docker.lab"
            docker.vm.synced_folder ".", "/vagrant_data", disabled: true

            docker.vm.network :private_network,         
                :libvirt__network_name => "ds_ct_net",    
                :libvirt__always_destroy => false,
                :ip => "10.10.10.1#{i}"

            docker.vm.provider :libvirt do |libvirt|
                libvirt.cpus = 2
                libvirt.memory = 2048
                libvirt.default_prefix = ""
            end

            docker.ssh.insert_key = false
            docker.ssh.private_key_path = ["~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
            
            if i == NODES_NUMBER
                docker.vm.provision :ansible do |ansible|
                    ansible.playbook = "main.yml"
                    ansible.limit = "all"
                    ansible.verbose = "vv"
                    # ansible.tags = "swarm"
                end
            end
        end
    end
end